name: py10
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.5=py312hca68cad_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.27.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h7900ff3_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libedit=3.1.20191231=he28a2e2_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=14.1.0=h77fa898_0
  - libgomp=14.1.0=h77fa898_0
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.5=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.1=h4bc722e_2
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=pyhd8ed1ab_0
  - platformdirs=4.3.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py312h9a8786e_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.12.4=h194c7f8_0_cpython
  - python_abi=3.12=5_cp312
  - pyzmq=26.2.0=py312hbf22597_0
  - readline=8.2=h8228510_1
  - setuptools=71.0.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py312h9a8786e_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h75354e8_4
  - zipp=3.20.1=pyhd8ed1ab_0
  - pip:
    - acvl-utils==0.2
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - albucore==0.0.20
    - albumentations==1.4.21
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - argparse==1.4.0
    - attrs==24.2.0
    - batchgenerators==0.25
    - batchgeneratorsv2==0.2
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - click==8.1.7
    - connected-components-3d==3.18.0
    - contourpy==1.2.1
    - cycler==0.12.1
    - dataclasses==0.6
    - deprecated==1.2.14
    - dicom2nifti==2.4.11
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - dynamic-network-architectures==0.3.1
    - efficientnet-pytorch==0.7.1
    - einops==0.8.0
    - eval-type-backport==0.2.0
    - fft-conv-pytorch==1.2.0
    - filelock==3.15.4
    - fonttools==4.53.1
    - frozenlist==1.4.1
    - fsspec==2024.6.1
    - future==1.0.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - h5py==3.11.0
    - huggingface-hub==0.26.3
    - humanize==4.10.0
    - hydra-core==1.3.2
    - idna==3.7
    - imagecodecs==2024.6.1
    - imagecorruptions==1.1.2
    - imageio==2.34.2
    - iopath==0.1.10
    - jinja2==3.1.4
    - joblib==1.4.2
    - kiwisolver==1.4.5
    - lazy-loader==0.4
    - lightning==2.4.0
    - lightning-utilities==0.11.8
    - linecache2==1.0.0
    - llvmlite==0.43.0
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.9.1
    - mdurl==0.1.2
    - mmsegmentation==1.2.2
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - munch==4.0.0
    - networkx==3.3
    - nibabel==5.2.1
    - nnunetv2==2.5.1
    - numba==0.60.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.82
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.10.0.84
    - p-tqdm==1.4.2
    - pandas==2.2.2
    - pathos==0.3.2
    - pillow==10.4.0
    - portalocker==2.10.1
    - pox==0.3.4
    - ppft==1.7.6.8
    - pretrainedmodels==0.7.4
    - prettytable==3.11.0
    - propcache==0.2.0
    - protobuf==5.28.2
    - pyarrow==17.0.0
    - pydantic==2.10.3
    - pydantic-core==2.27.1
    - pydicom==2.4.4
    - pynndescent==0.5.13
    - pyparsing==3.1.2
    - python-box==7.2.0
    - python-dateutil==2.9.0.post0
    - python-gdcm==3.0.24.1
    - python-graphviz==0.20.3
    - pytorch-lightning==2.4.0
    - pytz==2024.1
    - pyyaml==6.0.1
    - requests==2.32.3
    - rich==13.8.0
    - rt-utils==1.2.7
    - safetensors==0.4.5
    - sam-2==1.0
    - scikit-image==0.24.0
    - scikit-learn==1.5.1
    - scipy==1.14.0
    - seaborn==0.13.2
    - segmentation-models-pytorch==0.3.4
    - sentry-sdk==2.17.0
    - setproctitle==1.3.3
    - shellingham==1.5.4
    - simpleitk==2.3.1
    - simsimd==6.2.1
    - smmap==5.0.1
    - stringzilla==3.11.0
    - sympy==1.13.1
    - tensorboardx==2.6.2.2
    - threadpoolctl==3.5.0
    - tifffile==2024.7.24
    - timm==0.9.7
    - torch==2.4.0
    - torchinfo==1.8.0
    - torchio==0.19.9
    - torchmetrics==1.4.3
    - torchsummary==1.5.1
    - torchvision==0.19.0
    - totalsegmentator==2.4.0
    - tqdm==4.66.4
    - traceback2==1.4.0
    - triton==3.0.0
    - typer==0.12.5
    - tzdata==2024.1
    - umap-learn==0.5.7
    - unittest2==1.1.0
    - urllib3==2.2.2
    - wandb==0.18.3
    - wrapt==1.16.0
    - xvfbwrapper==0.2.9
    - yacs==0.1.8
    - yarl==1.15.4
prefix: /home/ubuntu/anaconda3/envs/py10
